name: Clicker
version: 1.0.0
main: kostamax27\Clicker\Main
api: 3.0.0

softdepend:
 - EconomyAPI
 - FormAPI
 
author: kostmax27

permissions:
  setclick.cmd:
    default: op
  delclick.cmd:
    default: op
  click.cmd:
    default: true
